# 🌐 TITAN CONFIG FILE
# File: /src/system/titan-config.yaml
# Description: Core configuration for Voro8 Context Engine & Cycle-2 flow
# Author: Brad Harris (brforeal)
# Updated: 2025-06-23

titan:
  cycle: 2
  title: Partnership
  numerology:
    value: 2
    theme: Collaboration and Balance
    phaseLabel: "Co-processing & Signal Sharing"
    next: 3
    signalDate: "2025-06-23"

identity:
  owner: brforeal
  active_roles:
    - brforeal@gmail.com
    - brforeal.dev@gmail.com
    - bmichaelh13@gmail.com
  alignment_tag: Navigator-2

tasks:
  - id: KPI_004
    name: Activate Partnership(1)
    focus: Assign Market Analyzer for trend reflection
  - id: KPI_005
    name: Activate Partnership(2)
    focus: Map camoflause logic with Knossos Navigator
  - id: KPI_006
    name: Activate Partnership(3)
    focus: Strengthen human–robot task clarity

phaseCore:
  current: 2
  map:
    1: Presence
    2: Partnership
    3: Creativity
    4: Reflection
    5: Correction
    6: Connection
    7: Rest
    8: Recalibration
    9: Release + Restart

context_engine:
  active: true
  memory_layer: MAL
  mindset_recursion: true
  status_log: "./logs/2025-06-23_onUpdate_TITAN-TALK.md"
  lastCheckpoint: 2025-06-23T09:22:00Z

directives:
  - Activate robot-task synergy
  - Trace camoflause logic per weekday
  - Align logs with numerology signal (Cycle-2)
  - Build momentum toward Cycle-3

export:
  toMarkdown: true
  toLogbook: true
  triggerOnEOD: true
